### ISSUE TITLE
Unerwartete Fehlermeldung, wenn die HTTPS-Anfrage an den Update-Server fehlschlägt

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#245]
## Erwartetes Verhalten

Beim Starten der Anwendung sucht Plotify nach neuen Versionen.
Dafür wird eine HTTPS-Anfrage an einen Webserver gesendet.
Wenn diese Anfrage fehlschlägt, soll dem Benutzer keine Fehlermeldung angezeigt werden.

## Tatsächliches Verhalten

Beim Starten der Anwendung sucht Plotify nach neuen Versionen.
Dafür wird eine HTTP(S)-Anfrage an einen Webserver gesendet.
Wenn diese Anfrage fehlschlägt, wird dem Benutzer das Dialogfenster für einen unerwarteten Fehler angezeigt:

```
TypeError: Cannot read property 'statusCode' of undefined
    at C:\Program Files\Plotify\resources\app.asar\shared\http.js:29:27
    at ClientRequest.<anonymous> (C:\Program Files\Plotify\resources\app.asar\node_modules\simple-get\index.js:73:21)
    at ClientRequest.f (C:\Program Files\Plotify\resources\app.asar\node_modules\once\once.js:25:25)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

## Umgebung

- Plotify-Version: 0.6.0-alpha.6
- Betriebssystem: Jedes

**Comment by SebastianSchmidt** [comment]
Der Fehler liegt in der Datei [http.js](https://github.com/plotify/plotify/blob/master/src/shared/http.js):

```js
if (error) {
  reject(error)
}

if (result.statusCode < 200 || result.statusCode > 299) {
  reject(new Error('HTTP status code: ' + result.statusCode))
}
```

Wenn ein Fehler aufgetreten ist und nachdem der Fehler zurückgemeldet worden ist, wird unnötigerweise versucht, den HTTP-Statuscode zu überprüfen. Da dieser nicht vorhanden ist tritt ein TypeError auf, der nicht abgefangen und deswegen als "Unerwarteter Fehler" an den Benutzer gemeldet wird.
